import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { events, eventDistances } from "./schema";

async function seedEvents() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    console.error("DATABASE_URL is required");
    process.exit(1);
  }

  const client = postgres(connectionString, { max: 1 });
  const db = drizzle(client);

  console.log("Seeding events...");

  const raceData = [
    {
      name: "Vancouver Marathon",
      slug: "vancouver-marathon",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-05-03"),
      city: "Vancouver",
      province: "BC",
      terrain: "road",
      description:
        "Experience one of the world's most scenic marathons through Vancouver's stunning waterfront, Stanley Park, and beautiful neighbourhoods. A Boston Qualifier course with incredible crowd support.",
      shortDescription: "Canada's most scenic marathon through Vancouver's waterfront and Stanley Park.",
      priceFromCad: 16000,
      priceToCad: 21000,
      registrationUrl: "https://bmovanmarathon.ca",
      websiteUrl: "https://bmovanmarathon.ca",
      organizerName: "RUNVAN",
      featured: true,
      avgTemperatureCelsius: 12,
      avgPrecipitationMm: 40,
      weatherNotes: "Usually mild and overcast. Occasional rain.",
      elevationGainMetres: 150,
      courseDescription:
        "Point-to-point through downtown, Stanley Park seawall, Kitsilano, UBC, and finishing at BC Place.",
      tags: ["bq-qualifier", "scenic", "medals", "pr-potential"],
      amenities: ["pacers", "hydration", "medals", "shirt", "expo"],
      distances: [
        { distance: "marathon", distanceKm: 42.2, distanceLabel: "Marathon", priceCad: 21000 },
        { distance: "half", distanceKm: 21.1, distanceLabel: "Half Marathon", priceCad: 16000 },
        { distance: "10k", distanceKm: 10, priceCad: 7500 },
        { distance: "5k", distanceKm: 5, priceCad: 5000 },
      ],
    },
    {
      name: "Ottawa Marathon",
      slug: "ottawa-marathon",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-05-24"),
      city: "Ottawa",
      province: "ON",
      terrain: "road",
      description:
        "Canada's capital marathon winds through historic Ottawa and Gatineau. The flat, fast course passes Parliament Hill, the Rideau Canal, and crosses into Quebec for a truly bilingual experience.",
      shortDescription: "Canada's capital marathon — flat, fast, and bilingual through Ottawa-Gatineau.",
      priceFromCad: 11000,
      priceToCad: 18000,
      registrationUrl: "https://www.runottawa.ca",
      websiteUrl: "https://www.runottawa.ca",
      organizerName: "Run Ottawa",
      featured: true,
      avgTemperatureCelsius: 17,
      avgPrecipitationMm: 75,
      weatherNotes: "Warm spring weather. Can be humid.",
      elevationGainMetres: 80,
      courseDescription:
        "A flat, fast loop through downtown Ottawa and Gatineau, passing Parliament Hill and the Rideau Canal.",
      tags: ["bq-qualifier", "flat", "pr-potential", "scenic"],
      amenities: ["pacers", "hydration", "medals", "shirt", "expo"],
      distances: [
        { distance: "marathon", distanceKm: 42.2, distanceLabel: "Marathon", priceCad: 18000 },
        { distance: "half", distanceKm: 21.1, distanceLabel: "Half Marathon", priceCad: 14000 },
        { distance: "10k", distanceKm: 10, priceCad: 7000 },
        { distance: "5k", distanceKm: 5, priceCad: 5000 },
        { distance: "custom", distanceKm: 2, distanceLabel: "2K", priceCad: 2500 },
      ],
    },
    {
      name: "Toronto Waterfront Marathon",
      slug: "toronto-waterfront-marathon",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-10-18"),
      city: "Toronto",
      province: "ON",
      terrain: "road",
      description:
        "Canada's largest marathon and a World Athletics Gold Label event. The fast, flat course along Lake Ontario's waterfront attracts elite runners from around the world.",
      shortDescription: "Canada's premier marathon — World Athletics Gold Label along Lake Ontario.",
      priceFromCad: 9500,
      priceToCad: 19500,
      registrationUrl: "https://www.torontowaterfrontmarathon.com",
      websiteUrl: "https://www.torontowaterfrontmarathon.com",
      organizerName: "Canada Running Series",
      featured: true,
      avgTemperatureCelsius: 10,
      avgPrecipitationMm: 55,
      weatherNotes: "Cool fall conditions. Ideal for racing.",
      elevationGainMetres: 50,
      courseDescription:
        "Fast, flat out-and-back along the Toronto waterfront, starting and finishing at City Hall.",
      tags: ["bq-qualifier", "flat", "pr-potential", "world-athletics"],
      amenities: ["pacers", "hydration", "medals", "shirt", "expo"],
      distances: [
        { distance: "marathon", distanceKm: 42.2, distanceLabel: "Marathon", priceCad: 19500 },
        { distance: "half", distanceKm: 21.1, distanceLabel: "Half Marathon", priceCad: 13500 },
        { distance: "10k", distanceKm: 10, priceCad: 6500 },
        { distance: "5k", distanceKm: 5, priceCad: 4500 },
      ],
    },
    {
      name: "Banff Marathon",
      slug: "banff-marathon",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-06-21"),
      city: "Banff",
      province: "AB",
      terrain: "road",
      description:
        "Run through the heart of the Canadian Rockies in Banff National Park. Stunning mountain scenery, wildlife, and crisp alpine air make this one of the most memorable races in North America.",
      shortDescription: "Run through the heart of the Canadian Rockies in Banff National Park.",
      priceFromCad: 11000,
      priceToCad: 17500,
      registrationUrl: "https://banffmarathon.com",
      websiteUrl: "https://banffmarathon.com",
      organizerName: "Banff Marathon",
      featured: true,
      avgTemperatureCelsius: 15,
      avgPrecipitationMm: 55,
      weatherNotes: "Alpine conditions — warm days, cool mornings. Pack layers.",
      elevationGainMetres: 400,
      courseDescription:
        "Point-to-point from the Trans-Canada Highway corridor into the town of Banff with Rocky Mountain views throughout.",
      tags: ["scenic", "mountains", "national-park", "medals"],
      amenities: ["hydration", "medals", "shirt"],
      distances: [
        { distance: "marathon", distanceKm: 42.2, distanceLabel: "Marathon", priceCad: 17500 },
        { distance: "half", distanceKm: 21.1, distanceLabel: "Half Marathon", priceCad: 14000 },
        { distance: "10k", distanceKm: 10, priceCad: 7000 },
      ],
    },
    {
      name: "Whistler Alpine Meadows Ultra",
      slug: "whistler-alpine-meadows-ultra",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-09-12"),
      city: "Whistler",
      province: "BC",
      terrain: "trail",
      description:
        "A challenging trail ultra through Whistler's alpine meadows and old-growth forest. Technical single-track, creek crossings, and massive elevation gain await experienced trail runners.",
      shortDescription: "Technical trail ultra through Whistler's alpine meadows and old-growth forest.",
      priceFromCad: 15000,
      priceToCad: 25000,
      registrationUrl: "https://whistleralpinemeadowsultra.com",
      websiteUrl: "https://whistleralpinemeadowsultra.com",
      organizerName: "Whistler Trail Running Society",
      featured: false,
      avgTemperatureCelsius: 10,
      avgPrecipitationMm: 60,
      weatherNotes: "Variable mountain weather. Rain and fog possible.",
      elevationGainMetres: 2800,
      courseDescription:
        "Single-track through Whistler's alpine meadows, old-growth forest, and mountain ridges.",
      tags: ["technical", "mountains", "scenic", "challenging"],
      amenities: ["hydration", "medals", "drop-bags"],
      distances: [
        { distance: "ultra", distanceKm: 80, distanceLabel: "80K Ultra", priceCad: 25000, cutoffTime: "16:00:00" },
        { distance: "ultra", distanceKm: 50, distanceLabel: "50K Ultra", priceCad: 20000, cutoffTime: "12:00:00" },
        { distance: "marathon", distanceKm: 42.2, distanceLabel: "Trail Marathon", priceCad: 15000 },
      ],
    },
    {
      name: "Montreal Marathon Oasis",
      slug: "montreal-marathon-oasis",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-09-20"),
      city: "Montreal",
      province: "QC",
      terrain: "road",
      description:
        "Montreal's premier road race showcases the city's vibrant neighbourhoods, iconic landmarks, and legendary crowd energy. Run through the Plateau, Old Montreal, and along the St. Lawrence River.",
      shortDescription: "Montreal's premier road race through iconic neighbourhoods and along the St. Lawrence.",
      priceFromCad: 8500,
      priceToCad: 16500,
      registrationUrl: "https://www.mtlmarathon.com",
      websiteUrl: "https://www.mtlmarathon.com",
      organizerName: "Marathon International de Montreal",
      featured: false,
      avgTemperatureCelsius: 15,
      avgPrecipitationMm: 65,
      weatherNotes: "Comfortable fall weather. Some wind along the river.",
      elevationGainMetres: 120,
      courseDescription:
        "Tour of Montreal's iconic neighbourhoods including the Plateau, Old Montreal, and the St. Lawrence waterfront.",
      tags: ["scenic", "urban", "pr-potential", "bilingual"],
      amenities: ["pacers", "hydration", "medals", "shirt", "expo"],
      distances: [
        { distance: "marathon", distanceKm: 42.2, distanceLabel: "Marathon", priceCad: 16500 },
        { distance: "half", distanceKm: 21.1, distanceLabel: "Half Marathon", priceCad: 11500 },
        { distance: "10k", distanceKm: 10, priceCad: 6000 },
        { distance: "5k", distanceKm: 5, priceCad: 4000 },
        { distance: "custom", distanceKm: 1, distanceLabel: "1K Kids", priceCad: 1500 },
      ],
    },
    {
      name: "Calgary Marathon",
      slug: "calgary-marathon",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-05-31"),
      city: "Calgary",
      province: "AB",
      terrain: "road",
      description:
        "Run along the Bow River pathway with views of the Rocky Mountain foothills. Calgary's race weekend offers distances for everyone and has been a prairie running tradition since 1964.",
      shortDescription: "A prairie running tradition since 1964 along the Bow River with mountain views.",
      priceFromCad: 7500,
      priceToCad: 15500,
      registrationUrl: "https://calgarymarathon.com",
      websiteUrl: "https://calgarymarathon.com",
      organizerName: "Calgary Marathon",
      featured: false,
      avgTemperatureCelsius: 14,
      avgPrecipitationMm: 60,
      weatherNotes: "Dry prairie weather. Can be windy. Sun exposure.",
      elevationGainMetres: 200,
      courseDescription:
        "Loop course along the Bow River pathway and through Calgary neighbourhoods.",
      tags: ["bq-qualifier", "scenic", "pr-potential"],
      amenities: ["pacers", "hydration", "medals", "shirt"],
      distances: [
        { distance: "marathon", distanceKm: 42.2, distanceLabel: "Marathon", priceCad: 15500 },
        { distance: "half", distanceKm: 21.1, distanceLabel: "Half Marathon", priceCad: 11500 },
        { distance: "10k", distanceKm: 10, priceCad: 6000 },
        { distance: "5k", distanceKm: 5, priceCad: 4000 },
      ],
    },
    {
      name: "Squamish 50",
      slug: "squamish-50",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-08-22"),
      city: "Squamish",
      province: "BC",
      terrain: "trail",
      description:
        "One of Canada's most iconic trail races through Squamish's rugged backcountry. Technical terrain, massive vertical gain, and breathtaking views of Howe Sound and the Coast Mountains.",
      shortDescription: "Iconic trail race through Squamish's rugged Coast Mountain backcountry.",
      priceFromCad: 13000,
      priceToCad: 22000,
      registrationUrl: "https://squamish50.com",
      websiteUrl: "https://squamish50.com",
      organizerName: "Squamish 50",
      featured: true,
      avgTemperatureCelsius: 18,
      avgPrecipitationMm: 30,
      weatherNotes: "Warm and dry. Creek crossings may be cold. Sun protection needed.",
      elevationGainMetres: 3100,
      courseDescription:
        "Technical single-track through old-growth forest, alpine terrain, and mountain ridges with views of Howe Sound.",
      tags: ["technical", "mountains", "scenic", "challenging", "iconic"],
      amenities: ["hydration", "medals", "drop-bags", "crew-access"],
      distances: [
        { distance: "ultra", distanceKm: 80, distanceLabel: "50 Mile", priceCad: 22000, cutoffTime: "17:00:00" },
        { distance: "ultra", distanceKm: 50, distanceLabel: "50K", priceCad: 17000, cutoffTime: "12:00:00" },
        { distance: "half", distanceKm: 23, distanceLabel: "23K", priceCad: 13000 },
      ],
    },
    {
      name: "Blue Nose Marathon",
      slug: "blue-nose-marathon",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-05-17"),
      city: "Halifax",
      province: "NS",
      terrain: "road",
      description:
        "Halifax's beloved road race along the harbour waterfront with Atlantic Ocean breezes and East Coast hospitality. One of the friendliest marathons in Canada.",
      shortDescription: "Halifax's beloved waterfront marathon with East Coast hospitality.",
      priceFromCad: 7000,
      priceToCad: 14000,
      registrationUrl: "https://bluenosemarathon.com",
      websiteUrl: "https://bluenosemarathon.com",
      organizerName: "Blue Nose Marathon",
      featured: false,
      avgTemperatureCelsius: 11,
      avgPrecipitationMm: 90,
      weatherNotes: "Cool Atlantic air. Wind and rain possible. Layers recommended.",
      elevationGainMetres: 250,
      courseDescription:
        "Waterfront loop through downtown Halifax, Point Pleasant Park, and along the harbour.",
      tags: ["scenic", "waterfront", "friendly", "east-coast"],
      amenities: ["pacers", "hydration", "medals", "shirt"],
      distances: [
        { distance: "marathon", distanceKm: 42.2, distanceLabel: "Marathon", priceCad: 14000 },
        { distance: "half", distanceKm: 21.1, distanceLabel: "Half Marathon", priceCad: 10000 },
        { distance: "10k", distanceKm: 10, priceCad: 5500 },
        { distance: "5k", distanceKm: 5, priceCad: 3500 },
      ],
    },
    {
      name: "Sinister 7 Ultra",
      slug: "sinister-7-ultra",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-07-11"),
      city: "Blairmore",
      province: "AB",
      terrain: "trail",
      description:
        "The Sinister 7 is a grueling 161 km relay or solo ultra through the Crowsnest Pass in the Canadian Rockies. Seven legs of rugged mountain terrain, creek crossings, and relentless climbing.",
      shortDescription: "Grueling 161K relay/solo ultra through the Crowsnest Pass in the Rockies.",
      priceFromCad: 20000,
      priceToCad: 55000,
      registrationUrl: "https://sinister7.com",
      websiteUrl: "https://sinister7.com",
      organizerName: "Sinister Sports",
      featured: false,
      avgTemperatureCelsius: 16,
      avgPrecipitationMm: 50,
      weatherNotes: "Mountain weather — hot valleys, cold summits. Thunderstorms possible.",
      elevationGainMetres: 6000,
      courseDescription:
        "Seven legs through the Crowsnest Pass: grizzly country, mountain summits, river crossings, and remote backcountry.",
      tags: ["challenging", "mountains", "relay", "remote", "iconic"],
      amenities: ["hydration", "drop-bags", "crew-access"],
      distances: [
        { distance: "ultra", distanceKm: 161, distanceLabel: "161K Solo", priceCad: 55000, cutoffTime: "30:00:00" },
        { distance: "ultra", distanceKm: 161, distanceLabel: "161K Relay (7-person)", priceCad: 20000 },
      ],
    },
    {
      name: "MEC Toronto Race Series: Spring",
      slug: "mec-toronto-race-spring",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-04-12"),
      city: "Toronto",
      province: "ON",
      terrain: "road",
      description:
        "MEC's popular race series returns to the Leslie Street Spit and Toronto waterfront. A flat, fast course ideal for PBs with great community energy.",
      shortDescription: "MEC's popular spring race on Toronto's flat waterfront — perfect for PBs.",
      priceFromCad: 4000,
      priceToCad: 5500,
      registrationUrl: "https://events.mec.ca",
      websiteUrl: "https://events.mec.ca",
      organizerName: "MEC Events",
      featured: false,
      avgTemperatureCelsius: 8,
      avgPrecipitationMm: 60,
      weatherNotes: "Early spring. Cool and breezy. Dress in layers.",
      elevationGainMetres: 15,
      courseDescription: "Flat out-and-back along the Martin Goodman Trail and Leslie Street Spit.",
      tags: ["flat", "pr-potential", "community", "beginner-friendly"],
      amenities: ["hydration", "medals"],
      distances: [
        { distance: "half", distanceKm: 21.1, distanceLabel: "Half Marathon", priceCad: 5500 },
        { distance: "10k", distanceKm: 10, priceCad: 4500 },
        { distance: "5k", distanceKm: 5, priceCad: 4000 },
      ],
    },
    {
      name: "Victoria Marathon",
      slug: "victoria-marathon",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-10-11"),
      city: "Victoria",
      province: "BC",
      terrain: "road",
      description:
        "Canada's most temperate marathon winds through Victoria's charming neighbourhoods, ocean views, and the famous Mile Zero. A fast Boston Qualifier with gorgeous fall scenery.",
      shortDescription: "Canada's most temperate marathon through Victoria's charming oceanside streets.",
      priceFromCad: 8000,
      priceToCad: 15000,
      registrationUrl: "https://runvictoriamarathon.com",
      websiteUrl: "https://runvictoriamarathon.com",
      organizerName: "Victoria Marathon Society",
      featured: false,
      avgTemperatureCelsius: 11,
      avgPrecipitationMm: 45,
      weatherNotes: "Mild, possibly overcast. Some ocean wind.",
      elevationGainMetres: 180,
      courseDescription:
        "Scenic route through James Bay, Dallas Road waterfront, Oak Bay, and finishing at the Legislature.",
      tags: ["bq-qualifier", "scenic", "oceanfront", "pr-potential"],
      amenities: ["pacers", "hydration", "medals", "shirt"],
      distances: [
        { distance: "marathon", distanceKm: 42.2, distanceLabel: "Marathon", priceCad: 15000 },
        { distance: "half", distanceKm: 21.1, distanceLabel: "Half Marathon", priceCad: 10000 },
        { distance: "10k", distanceKm: 10, priceCad: 5500 },
        { distance: "custom", distanceKm: 8, distanceLabel: "8K", priceCad: 4500 },
      ],
    },
    {
      name: "Quebec City Marathon SSQ",
      slug: "quebec-city-marathon",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-10-04"),
      city: "Quebec City",
      province: "QC",
      terrain: "road",
      description:
        "Run through the cobblestone streets of Old Quebec, a UNESCO World Heritage site. Challenging hills but incredible atmosphere through one of North America's oldest cities.",
      shortDescription: "Run through UNESCO-listed Old Quebec's cobblestone streets and historic walls.",
      priceFromCad: 7500,
      priceToCad: 14000,
      registrationUrl: "https://marathondequebec.com",
      websiteUrl: "https://marathondequebec.com",
      organizerName: "Marathon SSQ de Quebec",
      featured: false,
      avgTemperatureCelsius: 8,
      avgPrecipitationMm: 70,
      weatherNotes: "Cool fall weather. Cobblestone sections — wear road shoes with grip.",
      elevationGainMetres: 350,
      courseDescription:
        "Through Old Quebec, along the St. Lawrence, and up the steep hills of the Haute-Ville.",
      tags: ["scenic", "historic", "hilly", "bilingual"],
      amenities: ["pacers", "hydration", "medals", "shirt", "expo"],
      distances: [
        { distance: "marathon", distanceKm: 42.2, distanceLabel: "Marathon", priceCad: 14000 },
        { distance: "half", distanceKm: 21.1, distanceLabel: "Half Marathon", priceCad: 10000 },
        { distance: "10k", distanceKm: 10, priceCad: 5500 },
        { distance: "5k", distanceKm: 5, priceCad: 3500 },
      ],
    },
    {
      name: "Hatley Park Trail Run",
      slug: "hatley-park-trail-run",
      eventType: "fun_run",
      status: "published",
      startDate: new Date("2026-06-14"),
      city: "Colwood",
      province: "BC",
      terrain: "trail",
      description:
        "A beginner-friendly trail run through the beautiful Hatley Park National Historic Site. Gentle forested paths, gardens, and ocean views make this perfect for first-time trail runners.",
      shortDescription: "Beginner-friendly trail run through Hatley Park's forests and gardens.",
      priceFromCad: 3500,
      priceToCad: 4500,
      registrationUrl: "https://hatleyparktrailrun.ca",
      websiteUrl: "https://hatleyparktrailrun.ca",
      organizerName: "Island Trail Running",
      featured: false,
      avgTemperatureCelsius: 16,
      avgPrecipitationMm: 20,
      weatherNotes: "Warm and dry. Shaded forest trails.",
      elevationGainMetres: 80,
      courseDescription:
        "Gentle forested trails through Hatley Park gardens and along the ocean shoreline.",
      tags: ["beginner-friendly", "scenic", "family", "dog-friendly"],
      amenities: ["hydration", "medals"],
      distances: [
        { distance: "10k", distanceKm: 10, priceCad: 4500 },
        { distance: "5k", distanceKm: 5, priceCad: 3500 },
      ],
    },
    {
      name: "Mississauga Marathon",
      slug: "mississauga-marathon",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-05-03"),
      city: "Mississauga",
      province: "ON",
      terrain: "road",
      description:
        "A fast, flat course through Mississauga's waterfront and parks. Popular BQ course with excellent organization and spectator support along the Credit River.",
      shortDescription: "Fast, flat BQ course through Mississauga's waterfront and Credit River.",
      priceFromCad: 7500,
      priceToCad: 14500,
      registrationUrl: "https://mississaugamarathon.com",
      websiteUrl: "https://mississaugamarathon.com",
      organizerName: "Mississauga Marathon",
      featured: false,
      avgTemperatureCelsius: 12,
      avgPrecipitationMm: 60,
      weatherNotes: "Spring weather. Can be cool in the morning.",
      elevationGainMetres: 60,
      courseDescription:
        "Flat loop through Mississauga's lakefront, Port Credit, and along the Credit River valley.",
      tags: ["bq-qualifier", "flat", "pr-potential"],
      amenities: ["pacers", "hydration", "medals", "shirt"],
      distances: [
        { distance: "marathon", distanceKm: 42.2, distanceLabel: "Marathon", priceCad: 14500 },
        { distance: "half", distanceKm: 21.1, distanceLabel: "Half Marathon", priceCad: 10000 },
        { distance: "10k", distanceKm: 10, priceCad: 5500 },
        { distance: "5k", distanceKm: 5, priceCad: 3500 },
      ],
    },
    {
      name: "Elk Island Ultra",
      slug: "elk-island-ultra",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-08-15"),
      city: "Fort Saskatchewan",
      province: "AB",
      terrain: "trail",
      description:
        "Run through Elk Island National Park alongside free-roaming bison. Gentle rolling terrain through boreal forest and prairie grassland. A unique Canadian trail experience.",
      shortDescription: "Trail race through Elk Island National Park alongside free-roaming bison.",
      priceFromCad: 8500,
      priceToCad: 15000,
      registrationUrl: "https://elkislandultra.ca",
      websiteUrl: "https://elkislandultra.ca",
      organizerName: "Alberta Trail Running",
      featured: false,
      avgTemperatureCelsius: 20,
      avgPrecipitationMm: 45,
      weatherNotes: "Warm prairie summer. Mosquitoes possible. Carry water.",
      elevationGainMetres: 400,
      courseDescription:
        "Rolling single-track through boreal forest and prairie grassland in Elk Island National Park.",
      tags: ["scenic", "national-park", "wildlife", "unique"],
      amenities: ["hydration", "medals"],
      distances: [
        { distance: "ultra", distanceKm: 50, distanceLabel: "50K", priceCad: 15000, cutoffTime: "10:00:00" },
        { distance: "marathon", distanceKm: 42.2, distanceLabel: "Trail Marathon", priceCad: 12500 },
        { distance: "half", distanceKm: 21.1, distanceLabel: "Half Marathon", priceCad: 8500 },
      ],
    },
    {
      name: "Around the Bay 30K",
      slug: "around-the-bay-30k",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-03-29"),
      city: "Hamilton",
      province: "ON",
      terrain: "road",
      description:
        "The oldest road race in North America (since 1894). This challenging 30K loops around Hamilton Harbour with the infamous Valley Inn Hill at km 25. A Canadian running institution.",
      shortDescription: "North America's oldest road race (since 1894) — 30K around Hamilton Harbour.",
      priceFromCad: 7500,
      priceToCad: 9500,
      registrationUrl: "https://bayrace.com",
      websiteUrl: "https://bayrace.com",
      organizerName: "Bay Race",
      featured: true,
      avgTemperatureCelsius: 5,
      avgPrecipitationMm: 65,
      weatherNotes: "Early spring — cold and potentially windy. Dress warm.",
      elevationGainMetres: 200,
      courseDescription:
        "Loop around Hamilton Harbour. Flat for 24K then the brutal Valley Inn Hill at 25K followed by a fast downhill finish.",
      tags: ["historic", "iconic", "challenging", "hilly"],
      amenities: ["pacers", "hydration", "medals", "shirt"],
      distances: [
        { distance: "custom", distanceKm: 30, distanceLabel: "30K", priceCad: 9500 },
        { distance: "5k", distanceKm: 5, priceCad: 3500 },
      ],
    },
    {
      name: "Winnipeg Police Service Half Marathon",
      slug: "winnipeg-police-half-marathon",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-05-03"),
      city: "Winnipeg",
      province: "MB",
      terrain: "road",
      description:
        "Winnipeg's major spring race along the Assiniboine River and through The Forks. Flat prairie course with strong community support and post-race pancake breakfast.",
      shortDescription: "Winnipeg's flat spring race along the Assiniboine River with post-race pancakes.",
      priceFromCad: 6500,
      priceToCad: 10000,
      registrationUrl: "https://wpshalfmarathon.ca",
      websiteUrl: "https://wpshalfmarathon.ca",
      organizerName: "WPS Half Marathon",
      featured: false,
      avgTemperatureCelsius: 10,
      avgPrecipitationMm: 45,
      weatherNotes: "Prairie spring. Can be windy and cool.",
      elevationGainMetres: 30,
      courseDescription:
        "Flat course along the Assiniboine River, through The Forks, and back through River Heights.",
      tags: ["flat", "community", "pr-potential", "charity"],
      amenities: ["hydration", "medals", "shirt"],
      distances: [
        { distance: "half", distanceKm: 21.1, distanceLabel: "Half Marathon", priceCad: 10000 },
        { distance: "10k", distanceKm: 10, priceCad: 5500 },
        { distance: "5k", distanceKm: 5, priceCad: 3500 },
      ],
    },
    {
      name: "Fredericton Marathon",
      slug: "fredericton-marathon",
      eventType: "race",
      status: "published",
      startDate: new Date("2026-05-10"),
      city: "Fredericton",
      province: "NB",
      terrain: "road",
      description:
        "A small-town marathon with big heart. Run along the beautiful Saint John River through New Brunswick's capital city. Friendly volunteers and a tight-knit running community.",
      shortDescription: "Small-town marathon with big heart along the beautiful Saint John River.",
      priceFromCad: 6000,
      priceToCad: 12000,
      registrationUrl: "https://frederictonmarathon.com",
      websiteUrl: "https://frederictonmarathon.com",
      organizerName: "Fredericton Marathon Inc.",
      featured: false,
      avgTemperatureCelsius: 12,
      avgPrecipitationMm: 70,
      weatherNotes: "Spring. Mild and potentially rainy.",
      elevationGainMetres: 150,
      courseDescription:
        "Scenic loop along the Saint John River trail and through Fredericton's tree-lined streets.",
      tags: ["scenic", "friendly", "small-town", "riverfront"],
      amenities: ["hydration", "medals", "shirt"],
      distances: [
        { distance: "marathon", distanceKm: 42.2, distanceLabel: "Marathon", priceCad: 12000 },
        { distance: "half", distanceKm: 21.1, distanceLabel: "Half Marathon", priceCad: 8000 },
        { distance: "10k", distanceKm: 10, priceCad: 5000 },
        { distance: "5k", distanceKm: 5, priceCad: 3000 },
      ],
    },
  ];

  for (const race of raceData) {
    const { distances, ...eventData } = race;

    const [newEvent] = await db
      .insert(events)
      .values(eventData)
      .onConflictDoNothing({ target: events.slug })
      .returning();

    if (newEvent && distances.length > 0) {
      for (const d of distances) {
        await db.insert(eventDistances).values({
          eventId: newEvent.id,
          distance: d.distance,
          distanceKm: d.distanceKm,
          distanceLabel: "distanceLabel" in d ? d.distanceLabel : undefined,
          priceCad: d.priceCad,
          cutoffTime: "cutoffTime" in d ? d.cutoffTime : undefined,
        });
      }
      console.log(`  Seeded: ${newEvent.name} (${distances.length} distances)`);
    } else if (!newEvent) {
      console.log(`  Skipped (already exists): ${eventData.name}`);
    }
  }

  console.log("Event seeding complete!");

  await client.end();
  process.exit(0);
}

seedEvents().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
